name: shorts-gen
channels:
  - defaults
dependencies:
  - python=3.9.5
  - ffmpeg=4.2.2
  - pip:
      - redvid==2.0.1
      - moviepy==1.0.3
      - scikit-image==0.21.0
      - apiclient==1.0.4
      - praw==7.7.1
      - httplib2==0.22.0
      - oauth2client==4.1.3
      - google-api-python-client==2.97.0
      - Pillow==9.5.0
